### ISSUE TITLE
Torch gives error

### ISSUE THREAD

**Issue by huzeyfecoskun** [Rudrabha/Wav2Lip#118]
from torch._C import *
ImportError: DLL load failed:

first of all 
     pip install requirements.txt 

is not working it gives error. i manually install all packages
then
i have cuda toolkit installed. but it keeps giving that error.

**Comment by prajwalkr** [comment]
Please describe the error in detail and how to reproduce it

**Comment by huzeyfecoskun** [comment]
i fixed problem with installing python 3.6.7
but another problem is here
pip install torch=1.1.0 is not working

this is working one

 pip install torch==1.1.0 torchvision==0.2.0 -f https://download.pytorch.org/whl/torch_stable.html

but my new problem is 

```
Traceback (most recent call last):
  File "inference.py", line 385, in <module>
    main()
  File "inference.py", line 347, in main
    tqdm(gen, total=int(np.ceil(float(len(mel_chunks)) / batch_size)))
  File "C:\Program Files\Python36\lib\site-packages\tqdm\std.py", line 1127, in __iter__
    for obj in iterable:
  File "inference.py", line 190, in datagen
    face_det_results = face_detect(frames)  # BGR2RGB for CNN face detection
  File "inference.py", line 131, in face_detect
    face_detection.LandmarksType._2D, flip_input=False, device=device
  File "E:\Downloads\Wav2Lip-master\face_detection\api.py", line 62, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "E:\Downloads\Wav2Lip-master\face_detection\detection\sfd\sfd_detector.py", line 24, in __init__
    model_weights = torch.load(path_to_detector)
  File "C:\Program Files\Python36\lib\site-packages\torch\serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\Program Files\Python36\lib\site-packages\torch\serialization.py", line 574, in _load
    result = unpickler.load()
  File "C:\Program Files\Python36\lib\site-packages\torch\serialization.py", line 537, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "C:\Program Files\Python36\lib\site-packages\torch\serialization.py", line 119, in default_restore_location
    result = fn(storage, location)
  File "C:\Program Files\Python36\lib\site-packages\torch\serialization.py", line 95, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Program Files\Python36\lib\site-packages\torch\serialization.py", line 79, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.
```

**Comment by huzeyfecoskun** [comment]
also i have cuda enabled device. but i stuck here so nothing produced yet.

**Comment by prajwalkr** [comment]
Your environment is not set up to use CUDA. That is, PyTorch is unable to use a CUDA device. This issue has nothing to do with Wav2Lip, I think.

**Comment by huzeyfecoskun** [comment]
torch's 1.6 version is not giving error with cuda device. or my other tensorflow projects also not give error with cuda. on the otherhand i set 
torch.load(checkpoint, map_location='cpu')
this also not works.

**Comment by prajwalkr** [comment]
In the current environment you have set up, you can try running another sample deep learning model (MNIST etc.) and see if it is using a GPU successfully. If not, the problem is at your end entirely.

**Comment by huzeyfecoskun** [comment]
anyway thanks for your help. i never able to run code because i think my device supports cuda 11. and i cant run pytorch on cuda11  and when i set it to cpu it doesnt matter its not working.
