### ISSUE TITLE
Training frozen / not running

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#215]
Hi 
I have preprocessed a mp4 file which generates the individual images into /lrs2_preprocessed/1/00001

When I run the following command:'
python color_syncnet_train.py --data_root /lrs2_preprocessed --checkpoint_dir checkpoints

Running results

**Comment by wowopc** [comment]
D:\Wav2Lip>python preprocess.py --data_root data_root/main --preprocessed_root lrs2_preprocessed/
Started processing for data_root/main with 1 GPUs
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:08<00:00,  2.73s/it]
Dumping audios...
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 20.57it/s]

D:\Wav2Lip>
D:\Wav2Lip>█CD/D D:/Wav2Lip
'█CD' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\Wav2Lip>CD/D D:/Wav2Lip

D:\Wav2Lip>python color_syncnet_train.py --data_root /lrs2_preprocessed --checkpoint_dir checkpoints
use_cuda: True
total trainable params 16435072
0it [00:00, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    exitcode = _main(fd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    mod_name, mod_spec, pkg_name, script_name)
    prepare(preparation_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    exitcode = _main(fd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    exitcode = _main(fd)
  File "<string>", line 1, in <module>
    _fixup_main_from_path(data['init_main_from_path'])
    exec(code, run_globals)
    prepare(preparation_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Wav2Lip\color_syncnet_train.py", line 4, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    exitcode = _main(fd)
    from models import SyncNet_color as SyncNet
    prepare(preparation_data)
    run_name="__mp_main__")
    run_name="__mp_main__")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
  File "D:\Wav2Lip\models\__init__.py", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    prepare(preparation_data)
    from .wav2lip import Wav2Lip, Wav2Lip_disc_qual
    _fixup_main_from_path(data['init_main_from_path'])
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    pkg_name=pkg_name, script_name=fname)
  File "D:\Wav2Lip\models\wav2lip.py", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    import torch
    run_name="__mp_main__")
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\__init__.py", line 81, in <module>
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    run_name="__mp_main__")
    from torch._C import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    pkg_name=pkg_name, script_name=fname)
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
ImportError: DLL load failed: 页面文件太小，无法完成操作。
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    exec(code, run_globals)
  File "D:\Wav2Lip\color_syncnet_train.py", line 4, in <module>
    pkg_name=pkg_name, script_name=fname)
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    from models import SyncNet_color as SyncNet
  File "D:\Wav2Lip\models\__init__.py", line 1, in <module>
  File "D:\Wav2Lip\color_syncnet_train.py", line 4, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    from models import SyncNet_color as SyncNet
    from .wav2lip import Wav2Lip, Wav2Lip_disc_qual
    exec(code, run_globals)
  File "D:\Wav2Lip\models\__init__.py", line 1, in <module>
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
  File "D:\Wav2Lip\color_syncnet_train.py", line 4, in <module>
    from .wav2lip import Wav2Lip, Wav2Lip_disc_qual
  File "D:\Wav2Lip\models\wav2lip.py", line 1, in <module>
    exec(code, run_globals)
    from models import SyncNet_color as SyncNet
  File "D:\Wav2Lip\models\wav2lip.py", line 1, in <module>
    import torch
  File "D:\Wav2Lip\color_syncnet_train.py", line 4, in <module>
  File "D:\Wav2Lip\models\__init__.py", line 1, in <module>
    import torch
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\__init__.py", line 81, in <module>
    from models import SyncNet_color as SyncNet
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\__init__.py", line 81, in <module>
    from .wav2lip import Wav2Lip, Wav2Lip_disc_qual
  File "D:\Wav2Lip\models\__init__.py", line 1, in <module>
    from torch._C import *
    from torch._C import *
  File "D:\Wav2Lip\models\wav2lip.py", line 1, in <module>
    from .wav2lip import Wav2Lip, Wav2Lip_disc_qual
ImportError: DLL load failed: 页面文件太小，无法完成操作。
ImportError: DLL load failed: 页面文件太小，无法完成操作。
    import torch
  File "D:\Wav2Lip\models\wav2lip.py", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\__init__.py", line 81, in <module>
    import torch
    from torch._C import *
ImportError: DLL load failed: 页面文件太小，无法完成操作。
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: 页面文件太小，无法完成操作。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
    exitcode = _main(fd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    exitcode = _main(fd)
Traceback (most recent call last):
    prepare(preparation_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
Traceback (most recent call last):
    prepare(preparation_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    exitcode = _main(fd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    _fixup_main_from_path(data['init_main_from_path'])
    run_name="__mp_main__")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
    exitcode = _main(fd)
    prepare(preparation_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    exitcode = _main(fd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    run_name="__mp_main__")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    pkg_name=pkg_name, script_name=fname)
    exitcode = _main(fd)
    prepare(preparation_data)
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    prepare(preparation_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    pkg_name=pkg_name, script_name=fname)
    mod_name, mod_spec, pkg_name, script_name)
    prepare(preparation_data)
    _fixup_main_from_path(data['init_main_from_path'])
    run_name="__mp_main__")
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    mod_name, mod_spec, pkg_name, script_name)
    exec(code, run_globals)
    _fixup_main_from_path(data['init_main_from_path'])
    pkg_name=pkg_name, script_name=fname)
    run_name="__mp_main__")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    run_name="__mp_main__")
  File "D:\Wav2Lip\color_syncnet_train.py", line 5, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    import audio
    run_name="__mp_main__")
    mod_name, mod_spec, pkg_name, script_name)
    pkg_name=pkg_name, script_name=fname)
  File "D:\Wav2Lip\color_syncnet_train.py", line 5, in <module>
    pkg_name=pkg_name, script_name=fname)
  File "D:\Wav2Lip\audio.py", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    import audio
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    import librosa
    pkg_name=pkg_name, script_name=fname)
    exec(code, run_globals)
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Wav2Lip\audio.py", line 1, in <module>
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\__init__.py", line 211, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
  File "D:\Wav2Lip\color_syncnet_train.py", line 5, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    import librosa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    from . import core
    mod_name, mod_spec, pkg_name, script_name)
    import audio
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\__init__.py", line 211, in <module>
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
  File "D:\Wav2Lip\audio.py", line 1, in <module>
  File "D:\Wav2Lip\color_syncnet_train.py", line 5, in <module>
    from . import core
    from .convert import *  # pylint: disable=wildcard-import
  File "D:\Wav2Lip\color_syncnet_train.py", line 5, in <module>
    exec(code, run_globals)
    import librosa
    import audio
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    import audio
  File "D:\Wav2Lip\color_syncnet_train.py", line 5, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\__init__.py", line 211, in <module>
  File "D:\Wav2Lip\audio.py", line 1, in <module>
    from .convert import *  # pylint: disable=wildcard-import
    from . import notation
  File "D:\Wav2Lip\audio.py", line 1, in <module>
    import audio
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import core
    import librosa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    import librosa
  File "D:\Wav2Lip\audio.py", line 1, in <module>
    from . import notation
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\__init__.py", line 211, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\__init__.py", line 211, in <module>
    import librosa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\__init__.py", line 83, in <module>
    from . import core
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
    from ..util.exceptions import ParameterError
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from . import core
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\__init__.py", line 83, in <module>
    from . import notation
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\utils.py", line 6, in <module>
    from .convert import *  # pylint: disable=wildcard-import
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    import scipy.ndimage
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\convert.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\utils.py", line 6, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\ndimage\__init__.py", line 153, in <module>
    from . import notation
    from . import notation
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    import scipy.ndimage
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\__init__.py", line 83, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from .interpolation import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from . import notation
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from .utils import *  # pylint: disable=wildcard-import
    from ..util.exceptions import ParameterError
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\ndimage\interpolation.py", line 37, in <module>
    from ..util.exceptions import ParameterError
    from scipy import special
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\utils.py", line 6, in <module>
    from . import _distributor_init
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\__init__.py", line 83, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\core\notation.py", line 8, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\__init__.py", line 83, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\special\__init__.py", line 636, in <module>
    import scipy.ndimage
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\_distributor_init.py", line 61, in <module>
    from .utils import *  # pylint: disable=wildcard-import
    from ..util.exceptions import ParameterError
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\ndimage\__init__.py", line 153, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\utils.py", line 6, in <module>
    from . import _basic
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\__init__.py", line 83, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\utils.py", line 6, in <module>
    from .interpolation import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    import scipy.ndimage
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\special\_basic.py", line 16, in <module>
    from .utils import *  # pylint: disable=wildcard-import
    import scipy.ndimage
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\ndimage\interpolation.py", line 37, in <module>
    self._handle = _dlopen(self._name, mode)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\ndimage\__init__.py", line 154, in <module>
    from . import orthogonal
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\util\utils.py", line 6, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from scipy import special
    from . import _distributor_init
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\special\orthogonal.py", line 81, in <module>
    from .measurements import *
    import scipy.ndimage
OSError: [WinError 1455] 页面文件太小，无法完成操作。
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\special\__init__.py", line 636, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\_distributor_init.py", line 61, in <module>
    from scipy import linalg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\ndimage\measurements.py", line 34, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\ndimage\__init__.py", line 153, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\linalg\__init__.py", line 194, in <module>
    from . import _basic
    from . import _ni_label
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    from .interpolation import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\special\_basic.py", line 16, in <module>
ImportError: DLL load failed: 页面文件太小，无法完成操作。
    from .misc import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\ndimage\interpolation.py", line 37, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\linalg\misc.py", line 4, in <module>
    from . import orthogonal
    self._handle = _dlopen(self._name, mode)
    from scipy import special
    from .lapack import get_lapack_funcs
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\special\orthogonal.py", line 81, in <module>
OSError: [WinError 1455] 页面文件太小，无法完成操作。
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\special\__init__.py", line 636, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\linalg\lapack.py", line 783, in <module>
    from scipy import linalg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\linalg\__init__.py", line 211, in <module>
    from scipy.linalg import _flapack
ImportError: DLL load failed: 页面文件太小，无法完成操作。
    from ._decomp_update import *
  File "_decomp_update.pyx", line 1, in init scipy.linalg._decomp_update
    from . import _basic
ImportError: DLL load failed: 页面文件太小，无法完成操作。
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\special\_basic.py", line 16, in <module>
    from . import orthogonal
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\special\orthogonal.py", line 81, in <module>
    from scipy import linalg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\linalg\__init__.py", line 211, in <module>
    from ._decomp_update import *
  File "_decomp_update.pyx", line 1, in init scipy.linalg._decomp_update
ImportError: DLL load failed: 页面文件太小，无法完成操作。
use_cuda: True
use_cuda: True
use_cuda: True
0it [00:05, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "color_syncnet_train.py", line 279, in <module>
    nepochs=hparams.nepochs)
  File "color_syncnet_train.py", line 149, in train
    for step, (x, mel, y) in prog_bar:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tqdm\std.py", line 1166, in __iter__
    for obj in iterable:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 9928, 15448, 15132, 12872, 15316, 9468, 13352, 8640, 16004, 7052, 15416, 3928, 7560) exited unexpectedly

**Comment by wowopc** [comment]
Ah, the page file is too small to complete the operation, but now it's stuck??? I really want to cry

C:\Users\Administrator>CD/D D:/Wav2Lip&&python color_syncnet_train.py --data_root lrs2_preprocessed/ --checkpoint_dir checkpoints/
use_cuda: True
total trainable params 16435072
0it [00:00, ?it/s]use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True
use_cuda: True


一直不动了

**Comment by wowopc** [comment]
![Uploading 00000111111111.1111111111111.PNG…]()

**Comment by wowopc** [comment]
![00000111111111 1111111111111](https://user-images.githubusercontent.com/23237930/108548402-c0786800-7326-11eb-8f31-bff0758de605.PNG)

**Comment by wowopc** [comment]
@prajwalkr Boss, help me

**Comment by wowopc** [comment]
This situation needs to be modified train.txt The path

![SharedScreenshot](https://user-images.githubusercontent.com/23237930/108607531-db68dc00-73fb-11eb-8d76-8d6a0fb05923.jpg)

**Comment by wowopc** [comment]
The preprocessing result is also correct
 
![SharedScreenshot](https://user-images.githubusercontent.com/23237930/108607614-6053f580-73fc-11eb-9046-a5d6f5baa0db.jpg)  Thank you very much for helping Xiaobai

**Comment by prajwalkr** [comment]
Make sure you give the path to the LRS2 preprocessed folder properly. Please paste your directory structure below.

**Comment by wowopc** [comment]
Yes, thank you very much for solving this problem... TXT file of the train is correct and the path will not be frozen

**Comment by eastchun** [comment]
@wowopc, How did you resolve your "not running" problem?
I got the same situation and all my paths appear to be correct, but its not running...
