### ISSUE TITLE
Face not detected

### ISSUE THREAD

**Issue by MaoPopovich** [Rudrabha/Wav2Lip#229]
I try inference.py with a face video and a video with an audio,then a bug occurred:
Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 250, in main
    total=int(np.ceil(float(len(mel_chunks))/batch_size)))):
  File "/home/qinghuamao/.conda/envs/faceswap/lib/python3.7/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "inference.py", line 113, in datagen
    face_det_results = face_detect(frames) # BGR2RGB for CNN face detection
  File "inference.py", line 92, in face_detect
    raise ValueError('Face not detected! Ensure the video contains a face in all the frames.')
ValueError: Face not detected! Ensure the video contains a face in all the frames.

**Comment by MaoPopovich** [comment]
yesterday I use a face video which is shot vertically（height>width）and it failed，today I use a video whose width is larger than height and it success，so I wonder if there is something important about the size of the video，thanks!

**Comment by prajwalkr** [comment]
It might be a weakness of the face detection model, I am not sure. Wav2Lip has no such constraints.
