### ISSUE TITLE
Error while trying with different video

### ISSUE THREAD

**Issue by Varun-Sundaram** [Rudrabha/Wav2Lip#234]
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 272
(80, 874)
Length of mel chunks: 324
  0% 0/3 [00:00<?, ?it/s]
  0% 0/17 [00:04<?, ?it/s]
Recovering from OOM error; New batch size: 8

  0% 0/34 [00:00<?, ?it/s]Recovering from OOM error; New batch size: 4

  0% 0/68 [00:00<?, ?it/s]
Recovering from OOM error; New batch size: 2

  0% 0/136 [00:00<?, ?it/s]
Recovering from OOM error; New batch size: 1

  0% 0/272 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 78, in face_detect
    predictions.extend(detector.get_detections_for_batch(np.array(images[i:i + batch_size])))
  File "/content/Wav2Lip/face_detection/api.py", line 66, in get_detections_for_batch
    detected_faces = self.face_detector.detect_from_batch(images.copy())
  File "/content/Wav2Lip/face_detection/detection/sfd/sfd_detector.py", line 42, in detect_from_batch
    bboxlists = batch_detect(self.face_detector, images, device=self.device)
  File "/content/Wav2Lip/face_detection/detection/sfd/detect.py", line 65, in batch_detect
    imgs = torch.from_numpy(imgs).float().to(device)
RuntimeError: CUDA error: an illegal memory access was encountered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 250, in main
    total=int(np.ceil(float(len(mel_chunks))/batch_size)))):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "inference.py", line 113, in datagen
    face_det_results = face_detect(frames) # BGR2RGB for CNN face detection
  File "inference.py", line 81, in face_detect
    raise RuntimeError('Image too big to run face detection on GPU. Please use the --resize_factor argument')
RuntimeError: Image too big to run face detection on GPU. Please use the --resize_factor argument
  0% 0/34 [00:08<?, ?it/s]
  0% 0/3 [00:16<?, ?it/s]

**Comment by Varun-Sundaram** [comment]
oh i didn't run the requirements.txt. Now it's working great.

**Comment by aylitat** [comment]
can you tell me more detail?
