### ISSUE TITLE
cffi library has no function, constant or global variable named 'sf_wchar_open'

### ISSUE THREAD

**Issue by FarangoJones** [Rudrabha/Wav2Lip#24]
I can't fix an error when I run the last step. I have installed all the dependencies indicated in the requirements file.
//////////

(Wav2Lip) D:\Users\Documents\Deepfakes\Wav2lip\Wav2Lip-master>python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face video.mp4 --audio audio.wav

Using cpu for inference.
Reading video frames...
Number of frames available for inference: 856
Traceback (most recent call last):
  File "inference.py", line 276, in <module>
    main()
  File "inference.py", line 221, in main
    wav = audio.load_wav(args.audio, 16000)
  File "D:\Users\Documents\Deepfakes\Wav2lip\Wav2Lip-master\audio.py", line 10, in load_wav
    return librosa.core.load(path, sr=sr)[0]
  File "C:\Users\.conda\envs\snek\lib\site-packages\librosa\core\audio.py", line 127, in load
    with sf.SoundFile(path) as sf_desc:
  File "C:\Users\.conda\envs\snek\lib\site-packages\soundfile.py", line 627, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\.conda\envs\snek\lib\site-packages\soundfile.py", line 1170, in _open
    openfunction = _snd.sf_wchar_open
AttributeError: cffi library 'C:\Users\.conda\envs\snek\Library\bin\sndfile.dll' has no function, constant or global variable named 'sf_wchar_open'

**Comment by FarangoJones** [comment]
Fixed by using Python 3.6.
