### ISSUE TITLE
Looping

### ISSUE THREAD

**Issue by mevers90** [Rudrabha/Wav2Lip#244]
I'm trying to sync a shorter video (~2min) with a longer audio (~6min). I keep receiving the following error: 

0% 0/80 [10:32<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 250, in main
    total=int(np.ceil(float(len(mel_chunks))/batch_size)))):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1127, in __iter__
    for obj in iterable:
  File "inference.py", line 113, in datagen
    face_det_results = face_detect(frames) # BGR2RGB for CNN face detection
  File "inference.py", line 92, in face_detect
    raise ValueError('Face not detected! Ensure the video contains a face in all the frames.')
ValueError: Face not detected! Ensure the video contains a face in all the frames.”

**Comment by mevers90** [comment]
To be clear, this occurs after it reaches 100%

**Comment by prajwalkr** [comment]
I think this is because some last few frames do not have a face in them. I suggest you crop out the last 0.5 - 1s of the input video and try again

**Comment by mevers90** [comment]
I tried that, no dice: 

100% 219/220 [09:48<00:02,  2.60s/it]
100% 220/220 [10:03<00:00,  2.75s/it]
  0% 0/37 [10:06<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 250, in main
    total=int(np.ceil(float(len(mel_chunks))/batch_size)))):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1127, in __iter__
    for obj in iterable:
  File "inference.py", line 113, in datagen
    face_det_results = face_detect(frames) # BGR2RGB for CNN face detection
  File "inference.py", line 92, in face_detect
    raise ValueError('Face not detected! Ensure the video contains a face in all the frames.')
ValueError: Face not detected! Ensure the video contains a face in all the frames.

**Comment by mevers90** [comment]
tried a different video and same thing. Only time it has worked, so far, is when I use a picture.

**Comment by prajwalkr** [comment]
Can you post your video here?
