### ISSUE TITLE
The file might be corrupted

### ISSUE THREAD

**Issue by 0x4139** [Rudrabha/Wav2Lip#425]
I've tried different version of python 3.6.0, 3.6.3, 3.6.15 the issue persists and i am not sure what exactly is corrupted.

```python
oad checkpoint from: checkpoints/wav2lip(1).pth███████████████████████████████████████████████████| 6/6 [00:42<00:00,  6.57s/it]
  0%|                                                                                                      | 0/1 [00:43<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 252, in main
    model = load_model(args.checkpoint_path)
  File "inference.py", line 171, in load_model
    checkpoint = _load(path)
  File "inference.py", line 165, in _load
    map_location=lambda storage, loc: storage)
  File "/home/x4139/.pyenv/versions/3.6.3/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/x4139/.pyenv/versions/3.6.3/lib/python3.6/site-packages/torch/serialization.py", line 581, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 695962 more bytes. The file might be corrupted.
```

**Comment by 0x4139** [comment]
seems like an issue with the one drive on firefox when downloading the model it gets corrupted somehow
