### ISSUE TITLE
Unable to load: wav2Lip.pth 

### ISSUE THREAD

**Issue by arunasank** [Rudrabha/Wav2Lip#441]
```
Load checkpoint from: checkpoints/wav2lip.pth
  0% 0/5 [00:57<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 252, in main
    model = load_model(args.checkpoint_path)
  File "inference.py", line 171, in load_model
    checkpoint = _load(path)
  File "inference.py", line 162, in _load
    checkpoint = torch.load(checkpoint_path)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0d'.
```

**Comment by sahilg06** [comment]
Try downloading wav2lip.pth again? it happened to me when the weights were not downloaded properly.

**Comment by prajwalraju** [comment]
This worked for me thank you.
