### ISSUE TITLE
"Number of frames available for inference: 0"

### ISSUE THREAD

**Issue by liu-bohan** [Rudrabha/Wav2Lip#469]
`
(wav2lip) root@dell:/data/liubohan/Wav2Lip# python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face sample_data/test1.mp4 --audio sample_data/test_CN.wav
`

And below are the errors I got. the same .mp4 file and the .wav file are workable on my local device, but after i built a new env on a new device, errors occur.

```
Using cpu for inference. 
Reading video frames...
Number of frames available for inference: 0
(80, 1819)
Length of mel chunks: 227
0it [00:00, ?it/s]                                                                  | 0/2 [00:00<?, ?it/s]
0%|                                                                                 | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 250, in main
    total=int(np.ceil(float(len(mel_chunks))/batch_size)))):
  File "/data/software/envs/wav2lip/lib/python3.6/site-packages/tqdm/std.py", line 1127, in __iter__
    for obj in iterable:
  File "inference.py", line 122, in datagen
    idx = 0 if args.static else i%len(frames)
ZeroDivisionError: integer division or modulo by zero
```

**Comment by liu-bohan** [comment]
and since the server has no GUI, I use `mediainfo sample_data/test1.mp4` double check the .mp4 file. Below are output for reference:

```
General
Complete name                            : sample_data/test1.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (mp42/mp41)
File size                                : 913 KiB
Duration                                 : 12 s 400 ms
Overall bit rate                         : 603 kb/s
Encoded date                             : UTC 2023-03-09 01:59:58
Tagged date                              : UTC 2023-03-09 01:59:58
TIM                                      : 0
TSC                                      : 10
TSZ                                      : 1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.1
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 3 frames
Format settings, GOP                     : M=1, N=30
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 12 s 400 ms
Bit rate                                 : 274 kb/s
Width                                    : 640 pixels
Height                                   : 368 pixels
Display aspect ratio                     : 1.739
Frame rate mode                          : Constant
Frame rate                               : 10.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.117
Stream size                              : 415 KiB (45%)
Language                                 : English
Encoded date                             : UTC 2023-03-09 01:59:58
Tagged date                              : UTC 2023-03-09 01:59:58
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 12 s 400 ms
Source duration                          : 12 s 480 ms
Bit rate mode                            : Constant
Bit rate                                 : 317 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 480 KiB (53%)
Source stream size                       : 484 KiB (53%)
Language                                 : English
Encoded date                             : UTC 2023-03-09 01:59:58
Tagged date                              : UTC 2023-03-09 01:59:58

```

**Comment by liangp1213** [comment]
How did you solve it in the end?

**Comment by liangp1213** [comment]
How did you solve it in the end?

**Comment by liu-bohan** [comment]
> How did you solve it in the end?

Since I have successfully built this project on my local device and this project doesn't need a setup.py procedure, so I just copy and paste my successful case of source code to the new device. Surprisingly, it works. 

I didn't alter any packages in my virtual env, which means the problem was somehow caused by the source code, I guess.

**Comment by liu-bohan** [comment]
> How did you solve it in the end?
If you have the same problem, I can share with you my successful case of source code. Hopefully, it helps you.

**Comment by kira2015** [comment]
Using cpu for inference.
Reading video frames...
Number of frames available for inference: 101
(80, 593)
Length of mel chunks: 182
  0%|                                                                                   | 0/2 [00:00<?, ?it/sKilled^C
root@dd420e5754ea:/app/Wav2Lip#
root@dd420e5754ea:/app/Wav2Lip# python inference.py --checkpoint_path checkpoints/wav2lip.pth --face "../input/inputx.mp4" --audio "../input/bazigar_part1.wav"
Using cpu for inference.
Reading video frames...
Number of frames available for inference: 101
(80, 593)
Length of mel chunks: 182
  0%|                                                                                   | 0/2 [00:00<?, ?it/sKilled                                                                                   | 0/7 [00:00<?, ?it/s]

Excuse me, do you know what the problem is?

**Comment by Pythonpa** [comment]
> 

ah,the same error.

**Comment by Pythonpa** [comment]
> > 
> 
> ah,the same error.

ok , I noticed that after waiting about 5-8 minutes, it seemed to download some models,

**Comment by kenny-hash** [comment]
I have the same problem, guess that new version of opencv changed something.
After I specify the requirements file and run pip install with specifical pip package, the error dismiss:
```
opencv-contrib-python==4.2.0.34
opencv-python==4.1.0.25
```
