### ISSUE TITLE
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given

### ISSUE THREAD

**Issue by Sumit5194** [Rudrabha/Wav2Lip#489]
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 786
Traceback (most recent call last):
  File "/*****/*****/****/Wav2Lip/inference.py", line 280, in <module>
    main()
  File "/*****/*****/****/Wav2Lip/Wav2Lip/inference.py", line 225, in main
    mel = audio.melspectrogram(wav)
  File "/*****/*****/****/Wav2Lip/Wav2Lip/audio.py", line 47, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D))) - hp.ref_level_db
  File "/*****/*****/****/Wav2Lip/Wav2Lip/audio.py", line 95, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "/*****/*****/****/Wav2Lip/audio.py", line 100, in _build_mel_basis
    return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given

**Comment by knight965** [comment]
me too ,help!!!!How did you solve it ？orz

**Comment by Harry5396** [comment]
edit audio.py at line 100:

to this: return librosa.filters.mel(sr=hp.sample_rate,n_fft=hp.n_fft, n_mels=hp.num_mels,fmin=hp.fmin, fmax=hp.fmax)
