### ISSUE TITLE
AttributeError: module 'cv2' has no attribute '_registerMatType'

### ISSUE THREAD

**Issue by 954L** [Rudrabha/Wav2Lip#491]
```bash
ERR>Traceback (most recent call last):
ERR>  File "inference.py", line 3, in <module>
ERR>    import scipy, cv2, os, sys, argparse, audio
ERR>  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 181, in <module>
ERR>    bootstrap()
ERR>  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 175, in bootstrap
ERR>    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
ERR>  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
ERR>    py_module = importlib.import_module(module_name)
ERR>  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
ERR>    return _bootstrap._gcd_import(name[level:], package, level)
ERR>  File "/usr/local/lib/python3.7/dist-packages/cv2/mat_wrapper/__init__.py", line 33, in <module>
ERR>    cv._registerMatType(Mat)
ERR>AttributeError: module 'cv2' has no attribute '_registerMatType'

```

**Comment by uiuuiu** [comment]
let's try
```
pip uninstall opencv-contrib-python
pip install opencv-contrib-python==4.2.0.34
```
In requirements file, it defined `opencv-contrib-python>=4.2.0.34` so it will install latest version of opencv-contrib-python and cause this error

**Comment by 954L** [comment]
> let's try
> 
> ```
> pip uninstall opencv-contrib-python
> pip install opencv-contrib-python==4.2.0.34
> ```
> 
> In requirements file, it defined `opencv-contrib-python>=4.2.0.34` so it will install latest version of opencv-contrib-python and cause this error

Thanks!
