### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by sabareeshmj** [Rudrabha/Wav2Lip#513]
Traceback (most recent call last):

File "inference.py", line 7, in <module>

import torch, face_detection

File "C:\Users\wwwsh\OneDrive\Desktop\sabareesh\venv\lib\site-packages\torch\__init__.py", line 81, in <module>

from torch._C import *

ImportError: DLL load failed: The specified procedure could not be found.

**Comment by fvthakor** [comment]
yes, I am getting same issue in window 
![image](https://github.com/Rudrabha/Wav2Lip/assets/42373267/0a59f2fc-1aad-417a-a05d-cb861b601c51)

**Comment by Elsaam2y** [comment]
Try to make sure you are suing a proper python version, in this case 3.6 is recommended, and also check your torch and CUDA installation. This could be the problem.
