### ISSUE TITLE
改了 hparams.py 里的 img_size=256，报错了，是还要该其它地方的代码数据吗？Changed img_size=256 in hparams.py, reported an error, do you want code data from other places?

### ISSUE THREAD

**Issue by FXmonkey** [Rudrabha/Wav2Lip#519]
报错信息：(Error Msg:)
```
Traceback (most recent call last):
  File "wav2lip_train.py", line 371, in <module>
    train(device, model, train_data_loader, test_data_loader, optimizer,
  File "wav2lip_train.py", line 220, in train
    g = model(indiv_mels, x)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/Wav2Lip/models/wav2lip.py", line 112, in forward
    raise e
  File "/root/autodl-tmp/Wav2Lip/models/wav2lip.py", line 108, in forward
    x = torch.cat((x, feats[-1]), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 6 and 1 (The offending index is 0)
```

**Comment by Canyao45** [comment]
模型结构也要修改相应的大小

**Comment by FXmonkey** [comment]
@Canyao45 感谢，请问有具体参考吗，我看过 wav2lip_288×288，但那个的训练也没跑起来，还是不明白

**Comment by Canyao45** [comment]
这个就得看你的设备了288那个对硬件也有要求的

**Comment by guozhencs** [comment]
@Canyao45 模型结构怎么调呢？

**Comment by HaSaKiYasuooo** [comment]
> @Canyao45模型结构怎么调呢？

同问，288x288模型结构怎么调，GPT提示模型结构不同

**Comment by EricKong1985** [comment]
标记一下
