### ISSUE TITLE
can not run preprocess.py ,the error is  :RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by codersun123** [Rudrabha/Wav2Lip#534]
Traceback (most recent call last):
  File "D:\video_talk\Wav2Lip-master/preprocess.py", line 92, in mp_handler
    process_video_file(vfile, args, gpu_id)
  File "D:\video_talk\Wav2Lip-master/preprocess.py", line 66, in process_video_file
    preds = fa[gpu_id].get_detections_for_batch(np.asarray(fb))
  File "D:\video_talk\Wav2Lip-master\face_detection\api.py", line 73, in get_detections_for_batch
    detected_faces = self.face_detector.detect_from_batch(images.copy())
  File "D:\video_talk\Wav2Lip-master\face_detection\detection\sfd\sfd_detector.py", line 42, in detect_from_batch
    bboxlists = batch_detect(self.face_detector, images, device=self.device)
  File "D:\video_talk\Wav2Lip-master\face_detection\detection\sfd\detect.py", line 69, in batch_detect
    olist = net(imgs)
  File "C:\ProgramData\Anaconda3\envs\BFMTOFLAME36\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\video_talk\Wav2Lip-master\face_detection\detection\sfd\net_s3fd.py", line 129, in forward
    cls1 = torch.cat([bmax, chunk[3]], dim=1)
RuntimeError: CUDA error: an illegal memory access was encountered

bmax, chunk[3]] .shape is [1,1,270,480]

**Comment by codersun123** [comment]
[environmental problem](javascript:;)

**Comment by codersun123** [comment]
environmental problem
