### ISSUE TITLE
convert to ONNX and inference

### ISSUE THREAD

**Issue by aniketzz** [Rudrabha/Wav2Lip#540]
I am able to convert to ONNX but unable to infer using the ONNX.

here is the torch2onnx code:

```
import torch
import torch.onnx
from models import Wav2Lip

model = Wav2Lip()
checkpoint_path = "checkpoints/wav2lip.pth"
modelz = torch.load(checkpoint_path)

# device = 'cuda' if torch.cuda.is_available() else 'cpu'
device="cuda"
s = modelz["state_dict"]
new_s = {}
for k, v in s.items():
    new_s[k.replace('module.', '')] = v


model.load_state_dict(new_s)
model = model.to(device)

model.eval()
# print(model.eval())
input_shape1 = [(8, 1, 80, 16)]
input_shape2 = [(8, 6, 96, 96)]


torch.onnx.export(model,
                  (torch.randn(input_shape1).cuda(), torch.randn(input_shape2).cuda()),
                  "checkpoints/wav2lip.onnx",
                  input_names=["mel_spectrogram", "video_frames"],
                  output_names=["predicted_frames"],
                  verbose=True)
print("Done !!")
```
I am not sure about the input names though. I tried to infer and got following error.

```
Traceback (most recent call last):
  File "wav2lip_onnx.py", line 283, in <module>
    main()
  File "wav2lip_onnx.py", line 265, in main
    pred = ort_session.run(None, input_feed)
  File "/home/tg-30/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
TypeError: run(): incompatible function arguments. The following argument types are supported:
    1. (self: onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession, arg0: List[str], arg1: Dict[str, object], arg2: onnxruntime.capi.onnxruntime_pybind11_state.RunOptions) -> List[object]
```

**Comment by aniketzz** [comment]
Found the solution, I was giving batch size as 8, but the batch size is supposed to be dynamic. 

Here is the working code:

```
import torch
import torch.onnx
from models import Wav2Lip

model = Wav2Lip()
checkpoint_path = "checkpoints/wav2lip.pth"
modelz = torch.load(checkpoint_path)

# device = 'cuda' if torch.cuda.is_available() else 'cpu'
device="cuda"
s = modelz["state_dict"]
new_s = {}
for k, v in s.items():
    new_s[k.replace('module.', '')] = v


model.load_state_dict(new_s)
model = model.to(device)

model.eval()
# print(model.eval())
input_shape1 = (8, 1, 80, 16)
input_shape2 = (8, 6, 96, 96)

dynamic_axes = {'mel_spectrogram': {0: 'batch_size'}, 'video_frames': {0: 'batch_size'}}

torch.onnx.export(model,
                  (torch.randn(*input_shape1, device=device), torch.randn(*input_shape2, device=device)),
                  "checkpoints/wav2lip_1.onnx",
                  input_names=["mel_spectrogram", "video_frames"],
                  output_names=["predicted_frames"],
                  dynamic_axes=dynamic_axes,
                  verbose=True)
print("Done !!")
```
