### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by 2002NaveenKumar** [Rudrabha/Wav2Lip#541]
Model loaded
100%|████████████████████████████████████████████████████████████████████████████████| 4/4 [1:14:39<00:00, 1119.84s/it]
Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 277, in main
    subprocess.call(command, shell=platform.system() != 'Windows')
  File "C:\Users\Naveenkumar\AppData\Local\anaconda3\envs\python-wav2lip\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Naveenkumar\AppData\Local\anaconda3\envs\python-wav2lip\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Naveenkumar\AppData\Local\anaconda3\envs\python-wav2lip\lib\subprocess.py", line 1017, in _execute_child 
      startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by 2002NaveenKumar** [comment]
Anyone knows how to correct this error....

**Comment by 2002NaveenKumar** [comment]
I corrected the error....this error arises because it have used **ffmpeg.exe** which consist of **0 bytes** in it. 
In case if the below error occurs 
**OSError: [WinError 193] %1 is not a valid Win32 application** 

Try to download the **.exe** file again from the known source.
Even if you download it again the same error follows back. This is because the improper extraction of the **.exe** file.
When I downloaded the **ffmpeg** for **Windows**. It is downloaded in the format of **WinRAR archive (.7z)**. If u try to extract the files from this format you won't get the proper **ffmpeg.exe**. So, try to convert **WinRAR archive (.7z)** to **.zip** and then extract in the folder you want.
This worked for me.

Hope this would be useful!!!
