### ISSUE TITLE
用预模型请解决下报错

### ISSUE THREAD

**Issue by bluesfeng-feng** [Rudrabha/Wav2Lip#571]
Number of frames available for inference: 373
Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 225, in main
    mel = audio.melspectrogram(wav)
  File "/root/W字幕君交流场所Lip/audio.py", line 47, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D))) - hp.ref_level_db
  File "/root/W字幕君交流场所Lip/audio.py", line 95, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "/root/W字幕君交流场所Lip/audio.py", line 100, in _build_mel_basis
    return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given

**Comment by Smit-VI** [comment]
https://www.youtube.com/watch?v=P4PXI4Cx3hc&t=153s follow this video

**Comment by Leungsiuyin** [comment]
把根目录下audio.py 第 100行改成 : `return librosa.filters.mel(sr=hp.sample_rate, n_fft=hp.n_fft, n_mels=hp.num_mels, fmin=hp.fmin, fmax=hp.fmax)`

**Comment by lishiqi777** [comment]
上万高清中文数据集训练出来的256高清模型，含推理代码，oonx加速推理。
需要+V  tke365  先看效果再做决定
