### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by diogoalmeida1991** [Rudrabha/Wav2Lip#591]
Operating System: Windows 10.
Miniconda version: conda 23.5.2 running in administrator mode.
libs:
# Name                    Version                   Build  Channel
audioread                 3.0.1                    pypi_0    pypi
certifi                   2021.5.30        py36haa95532_0
cffi                      1.15.1                   pypi_0    pypi
dataclasses               0.8                      pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
joblib                    1.1.1                    pypi_0    pypi
librosa                   0.7.0                    pypi_0    pypi
llvmlite                  0.31.0                   pypi_0    pypi
numba                     0.48.0                   pypi_0    pypi
numpy                     1.17.1                   pypi_0    pypi
opencv-contrib-python     4.2.0.34                 pypi_0    pypi
opencv-python             4.1.0.25                 pypi_0    pypi
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.2           py36haa95532_0
pycparser                 2.21                     pypi_0    pypi
python                    3.6.13               h3758d61_0
resampy                   0.3.1                    pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                58.0.4           py36haa95532_0
six                       1.16.0                   pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
threadpoolctl             3.1.0                    pypi_0    pypi
torch                     1.10.2                   pypi_0    pypi
torchvision               0.3.0                    pypi_0    pypi
tqdm                      4.45.0                   pypi_0    pypi
typing-extensions         4.1.1                    pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py36h7fe50ca_0

Error:
Using cpu for inference.
Reading video frames...
Number of frames available for inference: 2969
(80, 150)
Length of mel chunks: 52
  0%|                                                                                                                                                                           | 0/1 [00:00<?, ?it/s]
  0%|                                                                                                                                                                           | 0/4 [00:00<?, ?it/s]
 25%|████████████████████████████████████████▊                                                                                                                          | 1/4 [00:29<01:29, 29.89s/it]
 50%|█████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 2/4 [00:59<00:59, 29.87s/it]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                        | 3/4 [01:29<00:29, 29.80s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:36<00:00, 24.17s/it]
Load checkpoint from: checkpoints
  0%|                                                                                                                                                                           | 0/1 [01:37<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 252, in main
    model = load_model(args.checkpoint_path)
  File "inference.py", line 171, in load_model
    checkpoint = _load(path)
  File "inference.py", line 165, in _load
    map_location=lambda storage, loc: storage)
  File "..\envs\wav2lip\lib\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "..\envs\wav2lip\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "..\envs\wav2lip\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'checkpoints'

Note: I didn't understand why i need put the folder of checkpoints in the command, is unnecessary and a point of fault for a inexperienced user. It is important for advanced user, so it must to be optional.

**Comment by diogoalmeida1991** [comment]
I solved here, in checkpoint you're refer about the method of training used, and I understand the reason of this parameter. I was using the directory only and not the achive pth that must to be appointed.
