### ISSUE TITLE
TypeError: 'tuple' object does not support item assignment

### ISSUE THREAD

**Issue by SerJamie** [Rudrabha/Wav2Lip#596]
tmp_dir/pyavi/wav2lip/video.avi-00234; 1 dets; 24.97 Hz
tmp_dir/pyavi/wav2lip/video.avi-00235; 1 dets; 25.01 Hz
tmp_dir/pyavi/wav2lip/video.avi-00236; 1 dets; 25.50 Hz
tmp_dir/pyavi/wav2lip/video.avi-00237; 1 dets; 24.78 Hz
tmp_dir/pyavi/wav2lip/video.avi-00238; 1 dets; 25.25 Hz
tmp_dir/pyavi/wav2lip/video.avi-00239; 1 dets; 25.31 Hz
tmp_dir/pyavi/wav2lip/video.avi-00240; 1 dets; 24.97 Hz
tmp_dir/pyavi/wav2lip/video.avi-00241; 1 dets; 25.26 Hz
tmp_dir/pyavi/wav2lip/video.avi-00242; 1 dets; 23.38 Hz
Traceback (most recent call last):
  File "/data/talkingface_test/Wav2Lip/syncnet_python/run_pipeline.py", line 298, in <module>
    scene = scene_detect(opt)
  File "/data/talkingface_test/Wav2Lip/syncnet_python/run_pipeline.py", line 235, in scene_detect
    scene_manager.detect_scenes(frame_source=video_manager)
  File "/data/anaconda3/envs/metric/lib/python3.9/site-packages/scenedetect/scene_manager.py", line 469, in detect_scenes
    self._process_frame(self._num_frames + start_frame, frame_im)
  File "/data/anaconda3/envs/metric/lib/python3.9/site-packages/scenedetect/scene_manager.py", line 366, in _process_frame
    self._add_cuts(detector.process_frame(frame_num, frame_im))
  File "/data/anaconda3/envs/metric/lib/python3.9/site-packages/scenedetect/detectors/content_detector.py", line 100, in process_frame
    curr_hsv[i] = curr_hsv[i].astype(numpy.int32)
TypeError: 'tuple' object does not support item assignment

Could anyone tell me how to solve this issue? Thanks a lot.

**Comment by jematy** [comment]
Do you solve this problem?

**Comment by SerJamie** [comment]
> Do you solve this problem?
I converted 'tuple' to 'list' ,and then converted them back to what they were.

**Comment by jematy** [comment]
> > Do you solve this problem?
> > I converted 'tuple' to 'list' ,and then converted them back to what they were.

thank you

**Comment by conkeur** [comment]
https://github.com/JasperLS/Understanding_Videos_at_Scale/issues/1
try 

> pip install scenedetect==0.6.0
