### ISSUE TITLE
Version incompatibility in librosa results in an arity error when calling librosa.filters.mel()

### ISSUE THREAD

**Issue by usergenic** [Rudrabha/Wav2Lip#627]
Ran for the first time on Colab tonight and got this error running the cell with inferece.py
```
Traceback (most recent call last):
  File "/content/Wav2Lip/inference.py", line 280, in <module>
    main()
  File "/content/Wav2Lip/inference.py", line 225, in main
    mel = audio.melspectrogram(wav)
  File "/content/Wav2Lip/audio.py", line 47, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D))) - hp.ref_level_db
  File "/content/Wav2Lip/audio.py", line 95, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "/content/Wav2Lip/audio.py", line 100, in _build_mel_basis
    return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given
```

**Comment by black-device** [comment]
did you manage to get it working?

**Comment by dwanggit** [comment]
+1, librosa version issue

**Comment by black-device** [comment]
I have only been able to make it work by downloading my virtual machine to Ubuntu 18.04, from there the versions of the repositories adapt to the project... I hope it helps.

**Comment by tmc** [comment]
librosa changed mel to force all arguments to be named (but supplying * as the first/only positional arg). You can see what's needed about changing that call in https://github.com/tmc/Wav2Lip/commit/00646c4745f364873d3a1aa3c142820a91ca4b65
