### ISSUE TITLE
Changing the image size causes the cosine similarity loss calculation to fail during discriminator training

### ISSUE THREAD

**Issue by seantempesta** [Rudrabha/Wav2Lip#65]
Hello.  I'm attempting to retrain the discriminator on higher quality images (96 -> 128) and I'm getting the following error:

```
total trainable params 16435072
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "color_syncnet_train.py", line 281, in <module>
    nepochs=hparams.nepochs)
  File "color_syncnet_train.py", line 163, in train
    loss = cosine_loss(a, v, y)
  File "color_syncnet_train.py", line 135, in cosine_loss
    d = nn.functional.cosine_similarity(a, v)
RuntimeError: The size of tensor a (512) must match the size of tensor b (2048) at non-singleton dimension 1
```

What other parts of the code needs to change to support higher resolution images?

**Comment by prajwalkr** [comment]
You need to change the model architecture to get a 1D vector at the end of the face_encoder. Your audio and face embeddings must be of the exact same shape.
