### ISSUE TITLE
AttributeError: module 'face_detection' has no attribute 'FaceAlignment'

### ISSUE THREAD

**Issue by liuchunyu524** [Rudrabha/Wav2Lip#656]
Traceback (most recent call last):
  File "preprocess.py", line 33, in <module>
    device='cuda:{}'.format(id)) for id in range(args.ngpu)]
  File "preprocess.py", line 33, in <listcomp>
    device='cuda:{}'.format(id)) for id in range(args.ngpu)]
AttributeError: module 'face_detection' has no attribute 'FaceAlignment'

(venv) (base) bash-4.2$ pip list
Package               Version
--------------------- --------
appdirs               1.4.4
audioread             3.0.1
certifi               2024.2.2
cffi                  1.15.1
charset-normalizer    2.0.12
decorator             5.1.1
face-detection        0.1.4
idna                  3.6
joblib                1.1.1
librosa               0.9.2
llvmlite              0.31.0
numba                 0.48.0
numpy                 1.17.1
opencv-contrib-python 4.3.0.38
opencv-python         4.3.0.38
packaging             21.3
Pillow                8.4.0
pip                   21.3.1
pooch                 1.6.0
pycparser             2.21
pyparsing             3.0.7
requests              2.27.1
resampy               0.3.1
scikit-learn          0.24.2
scipy                 1.5.4
setuptools            59.6.0
six                   1.16.0
soundfile             0.12.1
threadpoolctl         3.1.0
torch                 1.1.0
torchvision           0.3.0
tqdm                  4.45.0
urllib3               1.26.18

Python 3.6.5 :: Anaconda, Inc.

**Comment by tranthuhoai3786** [comment]
i got the same error. do you have any solution? @liuchunyu524

**Comment by tranthuhoai3786** [comment]
In audio.py, you can try:
import face_alignment
detector = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, 
											flip_input=False, device=device)

this work for me. @liuchunyu524

**Comment by lishiqi777** [comment]
高清中文数据集训练出来的256高清模型，含推理代码，oonx加速推理。需要+V  tke365  先看效果再做决定
