### ISSUE TITLE
训练syncnet报错：RuntimeError: DataLoader worker (pid 899437) is killed by signal: Segmentation fault. ，训练到第290000结束后报错：，请问有人遇到过这个问题吗？

### ISSUE THREAD

**Issue by Ko24Bewjw** [Rudrabha/Wav2Lip#662]
Traceback (most recent call last):
  File "color_syncnet_train.py", line 279, in &lt;module&gt;
    nepochs=hparams.nepochs)
  File "color_syncnet_train.py", line 163, in train
    optimizer.step()
  File "/home/user/anaconda3/envs/wav2lip/lib/python3.6/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/wav2lip/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/wav2lip/lib/python3.6/site-packages/torch/optim/adam.py", line 144, in step
    eps=group['eps'])
  File "/home/user/anaconda3/envs/wav2lip/lib/python3.6/site-packages/torch/optim/_functional.py", line 87, in adam
    exp_avg_sq.mul_(beta2).addcmul_(grad, grad.conj(), value=1 - beta2)
  File "/home/user/anaconda3/envs/wav2lip/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 899437) is killed by signal: Segmentation fault.

**Comment by chunyu-li** [comment]
Change your PyTorch version, I met same problem with 1.13.1. I recommend 2.0.1

**Comment by lishiqi777** [comment]
高清中文数据集训练出来的256高清模型，含推理代码，oonx加速推理。需要+V  tke365  先看效果再做决定
