### ISSUE TITLE
FileNotFoundError: [WinError 2] the specified file cannot be found

### ISSUE THREAD

**Issue by asgard13373** [Rudrabha/Wav2Lip#663]
///(I don't understand python and its libraries. my knowledge is limited to ctrl c + v, thanks in advance)

I installed the model and the checkpoint according to the instructions, and when generating the finished video, I got the following log:
 █████████████████████████████████████████████████████████████| 11/11 [01:18<00:00,  7.12s/it]
Traceback (most recent call last):
  File "C:\Users\asgar\Miniconda3\envs\wav2lip\lib\site-packages\gradio\routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "C:\Users\asgar\Miniconda3\envs\wav2lip\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\asgar\Miniconda3\envs\wav2lip\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "C:\Users\asgar\Miniconda3\envs\wav2lip\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\asgar\Miniconda3\envs\wav2lip\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\asgar\Miniconda3\envs\wav2lip\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Users\asgar\Miniconda3\envs\wav2lip\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\asgar\Miniconda3\envs\wav2lip\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "D:\hhh\wav2lip\ui.py", line 246, in generate
    inference("checkpoints/" + checkpoint + ".pth", video.name, grAudio.name, pads, resize_factor, no_smooth)
  File "D:\hhh\wav2lip\ui.py", line 219, in inference
    subprocess.call(command, shell=platform.system() != 'Windows')
  File "C:\Users\asgar\Miniconda3\envs\wav2lip\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\asgar\Miniconda3\envs\wav2lip\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\asgar\Miniconda3\envs\wav2lip\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл

**Comment by lishiqi777** [comment]
高清中文数据集训练出来的256高清模型，含推理代码，oonx加速推理。需要+V  tke365  先看效果再做决定

**Comment by aliazmn** [comment]
same issue any progress?

**Comment by UGarCil** [comment]
I ran into this issue when trying the Wav2Lip algorithm. Make sure to install your dependency (in my example ffmpeg) using `conda install ffmpeg`

The issue is likely caused by python trying to run a process in the command line for a module that doesn't have the binaries in the bin folder of your environment. In my case (Windows), it had to be in C:\Users\myname\.conda\envs\wav2lip\Library\bin\ffmpeg.exe

To test whether it's in your binaries, you can open the command prompt and type "where ffmpeg"
