### ISSUE TITLE
Traceback (most recent call last):   File "inference.py", line 280, in <module>     main()   File "inference.py", line 250, in main     total=int(np.ceil(float(len(mel_chunks))/batch_size)))):   File "D:\lq\anaconda3\envs\wav2lip\lib\site-packages\tqdm\std.py", line 1127, in __iter__     for obj in iterable:   File "inference.py", line 113, in datagen     face_det_results = face_detect(frames) # BGR2RGB for CNN face detection   File "inference.py", line 92, in face_detect     raise ValueError('Face not detected! Ensure the video contains a face in all the frames.') ValueError: Face not detected! Ensure the video contains a face in all the frames.

### ISSUE THREAD

**Issue by wuye901126** [Rudrabha/Wav2Lip#681]
Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 250, in main
    total=int(np.ceil(float(len(mel_chunks))/batch_size)))):
  File "D:\lq\anaconda3\envs\wav2lip\lib\site-packages\tqdm\std.py", line 1127, in __iter__
    for obj in iterable:
  File "inference.py", line 113, in datagen
    face_det_results = face_detect(frames) # BGR2RGB for CNN face detection
  File "inference.py", line 92, in face_detect
    raise ValueError('Face not detected! Ensure the video contains a face in all the frames.')
ValueError: Face not detected! Ensure the video contains a face in all the frames.

**Comment by abeermohamed1** [comment]
did you manage to fix this?
