### ISSUE TITLE
PEP 517

### ISSUE THREAD

**Issue by QuantumShot10** [Rudrabha/Wav2Lip#695]
While installing the requirement.txt file, I am facing this issue anybody here to help me .

  -- Installing: /tmp/pip-install-ejmsubce/opencv-contrib-python_7f7d3d8e654945a9b7894b8e34a9221f/_skbuild/linux-x86_64-3.6/cmake-install/share/opencv4/lbpcascades/lbpcascade_silverware.xml
  Copying files from CMake output
  creating directory _skbuild/linux-x86_64-3.6/cmake-install/cv2
  copying _skbuild/linux-x86_64-3.6/cmake-install/python/cv2/python-3/cv2.abi3.so -> _skbuild/linux-x86_64-3.6/cmake-install/cv2/cv2.abi3.so
  copying _skbuild/linux-x86_64-3.6/cmake-install/python/cv2/__init__.py -> _skbuild/linux-x86_64-3.6/cmake-install/cv2/__init__.py
  copying _skbuild/linux-x86_64-3.6/cmake-install/python/cv2/load_config_py2.py -> _skbuild/linux-x86_64-3.6/cmake-install/cv2/load_config_py2.py
  copying _skbuild/linux-x86_64-3.6/cmake-install/python/cv2/load_config_py3.py -> _skbuild/linux-x86_64-3.6/cmake-install/cv2/load_config_py3.py
  copying _skbuild/linux-x86_64-3.6/cmake-install/python/cv2/config.py -> _skbuild/linux-x86_64-3.6/cmake-install/cv2/config.py
  copying _skbuild/linux-x86_64-3.6/cmake-install/python/cv2/config-3.py -> _skbuild/linux-x86_64-3.6/cmake-install/cv2/config-3.py
  Traceback (most recent call last):
    File "/home/tignanshu/miniconda3/envs/lip/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/tignanshu/miniconda3/envs/lip/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/tignanshu/miniconda3/envs/lip/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-rlsbwwl0/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-rlsbwwl0/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-rlsbwwl0/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 268, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-rlsbwwl0/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 543, in <module>
      main()
    File "setup.py", line 316, in main
      cmake_source_dir=cmake_source_dir,
    File "/tmp/pip-build-env-rlsbwwl0/overlay/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 683, in setup
      cmake_install_dir,
    File "setup.py", line 456, in _classify_installed_files_override
      raise Exception("Not found: '%s'" % relpath_re)
  Exception: Not found: 'python/cv2/py.typed'
  ----------------------------------------
  ERROR: Failed building wheel for opencv-contrib-python
Successfully built librosa
Failed to build opencv-contrib-python
ERROR: Could not build wheels for opencv-contrib-python which use PEP 517 and cannot be installed directly

**Comment by Crystal1213** [comment]
同样遇到了该问题

**Comment by Crystal1213** [comment]
请问您是怎么解决的

**Comment by X-Terry** [comment]
the same as me，how deal with it?

**Comment by X-Terry** [comment]
python 3.6.13
opencv-contrib-python==4.3.0.38
opencv-python==4.3.0.38

**Comment by rickif** [comment]
> python 3.6.13 opencv-contrib-python==4.3.0.38 opencv-python==4.3.0.38

It works. Thanks
