### ISSUE TITLE
mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given

### ISSUE THREAD

**Issue by WachasWps** [Rudrabha/Wav2Lip#727]
127.0.0.1 - - [26/Dec/2024 02:23:10] "POST /ask HTTP/1.1" 500 -
Press CTRL+C to quit
127.0.0.1 - - [26/Dec/2024 02:32:03] "OPTIONS /ask HTTP/1.1" 200 -
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 1
Traceback (most recent call last):
  File "C:\Users\wacha\OneDrive\Desktop\Storage\avatar wav2lip\Wav2Lip\inference.py", line 280, in <module>
    main()
  File "C:\Users\wacha\OneDrive\Desktop\Storage\avatar wav2lip\Wav2Lip\inference.py", line 225, in main
    mel = audio.melspectrogram(wav)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wacha\OneDrive\Desktop\Storage\avatar wav2lip\Wav2Lip\audio.py", line 47, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D))) - hp.ref_level_db
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wacha\OneDrive\Desktop\Storage\avatar wav2lip\Wav2Lip\audio.py", line 95, in _linear_to_mel
    _mel_basis = _build_mel_basis()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\wacha\OneDrive\Desktop\Storage\avatar wav2lip\Wav2Lip\audio.py", line 100, in _build_mel_basis
    return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given
127.0.0.1 - - [26/Dec/2024 02:32:30] "POST /ask HTTP/1.1" 500 -

**Comment by bouldrini** [comment]
I encounter a very similar issue when executing following command in collab:

`!cd Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face "../sample_data/test.mp4" --audio "../sample_data/test.wav"`

Ill attach my collab-output:


```
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 375
Traceback (most recent call last):
  File "/content/Wav2Lip/inference.py", line 280, in <module>
    main()
  File "/content/Wav2Lip/inference.py", line 225, in main
    mel = audio.melspectrogram(wav)
  File "/content/Wav2Lip/audio.py", line 47, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D))) - hp.ref_level_db
  File "/content/Wav2Lip/audio.py", line 95, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "/content/Wav2Lip/audio.py", line 100, in _build_mel_basis
    return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given
```

**Comment by EzraApple** [comment]
The current code in `audio.py` that calls `librosa.filters.mel` :
```
def _build_mel_basis():
    assert hp.fmax <= hp.sample_rate // 2
    return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
                               fmin=hp.fmin, fmax=hp.fmax)
```

Newer `librosa` versions use keyword arguments for sample rate (`sr`) and number of FFT components (`n_fft`). A quick fix is replacing it with the following:
```
def _build_mel_basis():
    assert hp.fmax <= hp.sample_rate // 2
    return librosa.filters.mel(sr=hp.sample_rate, n_fft=hp.n_fft, n_mels=hp.num_mels,
                               fmin=hp.fmin, fmax=hp.fmax)
```
